/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("de.crazydev22.resources-ftp") version "1.1.0"
}

repositories {
    mavenCentral()

    maven {
        name = "papermc"
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
}

dependencies {
    api(libs.org.jetbrains.annotations)
    compileOnly(libs.io.papermc.paper.paper.api)

    compileOnly(libs.org.projectlombok.lombok)
    annotationProcessor(libs.org.projectlombok.lombok)
}

group = "de.neo8.jagil"
version = "4.0-beta.11"
description = "JAGIL"
java.sourceCompatibility = JavaVersion.VERSION_21

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }

    repositories {
        maven {
            name = "neo8ftp"
            url = uri("ftpes://repo.neo8.de:21/repo/")
            credentials(PasswordCredentials::class)
        }
    }
}
