/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenCentral()

    maven {
        name = "papermc"
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
}

dependencies {
    api(libs.org.jetbrains.annotations)
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.com.arcaniax.headdatabase.api)
    compileOnly(libs.com.h2database.h2)

    compileOnly(libs.org.projectlombok.lombok)
    annotationProcessor(libs.org.projectlombok.lombok)
}

group = "de.neo8.jagil"
version = "4.0-beta.49"
description = "JAGIL"
java.sourceCompatibility = JavaVersion.VERSION_21

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }

    repositories {
        maven {
            name = "keksServerRepositorySnapshots"
            url = uri("https://repo.keks-server.de/snapshots")
            credentials(PasswordCredentials::class)
        }
    }
}
