/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "JAGIL"

pluginManagement.repositories {
    maven {
        name = "neo8-repository"
        url = uri("https://repo.neo8.de/")
    }
}